### ISSUE TITLE
Nodejs14 support will end Jan 30th 2024

### ISSUE THREAD

**Issue by black-mirror-1** [haggman/HelloLoggingNodeJS#10]
Please update the Nodejs version as it is going to be out of support soon.

"WARNING: Node.js 14 is no longer supported by the Node.js community as of 30 April, 2023. Node.js 14 will be end of support on 2024-01-30. As of 2024-01-30 you will no longer be able to deploy your App Engine Standard using nodejs14. We recommend you to upgrade to the latest version of Node.js as soon as possible."

**Comment by haggman** [comment]
I updated to version 16 earlier last year (if I remember). Could it be you're working off an old version?

**Comment by black-mirror-1** [comment]
> I updated to version 16 earlier last year (if I remember). Could it be you're working off an old version?

It looks like you did update the Dockerfile. I was referring to the app.yaml that is still using nodejs and is giving that warning when its deployed to App Engine.

https://github.com/haggman/HelloLoggingNodeJS/blob/848667699b0cee49dafaabbc39edace159917ec4/app.yaml#L1

**Comment by haggman** [comment]
Finally did this update! Thanks.
